### ISSUE TITLE
Test suite is failing - Wanting to contribute

### ISSUE THREAD

**Issue by inooid** [goto-bus-stop/keyv-firestore#23]
👋   Heya! I'd like to contribute to keeping `keyv-firestore` up-to-date, but the test suite is currently failing. When running the test suite locally the tests are passing with my personal Cloud Firestore database (while testing https://github.com/goto-bus-stop/keyv-firestore/pull/20).

Is there any way that the current GitHub actions setup is missing some credentials or is wrongly configured over the years? Is there anything I can do to help out and keep this library up to date?

**Comment by goto-bus-stop** [comment]
I think the CI is fine, but keyv may have added more tests since i last worked on this? A lot of the tests _do_ pass, so the credentials should be good.

the CI will only work on branch runs I guess. if you're still interested in contributing, I can hand push access to the repo, so you can actually get changes run on CI.
